version: '3'
services:
  redis-server:
    image: redis
  fastapi:
    build: .
      # context: .
      # dockerfile: Dockerfile
    # volumes:
    #   - .:/application
    ports:
     - "80:8000"
  # test:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - .:/application